sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install:
  - git config --global user.name "$COMMIT_AUTHOR_NAME"
  - git config --global user.email "$COMMIT_AUTHOR_EMAIL"
  - export COMMIT_MESSAGE=`git log -1 --oneline`
  - mvn --settings .travis/settings.xml -B -V clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
