sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - .travis/before_install.sh

install:
  - mvn --settings .travis/settings.xml -B -V clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
