sudo: false

language: java

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - git config user.name "$COMMIT_AUTHOR_NAME"
  - git config user.email "$COMMIT_AUTHOR_EMAIL"
  - export COMMIT_MESSAGE=`git log -1 --oneline`
  - cp .travis.settings.xml $HOME/.m2/settings.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: mvn deploy -Pdeploy -DskipTests=true -B -V
    skip_cleanup: true
    on:
      branch: master
