sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gitconfig

before_install:
  - cp .travis/settings.xml $HOME/.m2/settings.xml

install: true

scritpt:
  - mvn --settings .travis/settings.xml -B -V -Prelease clean install
  - .travis/deploy.sh
  - mvn --settings .travis/settings.xml -B -V -Prelease release:prepare -DskipTests -Darguments="-DskipTests"
  - mvn --settings .travis/settings.xml -B -V -Prelease release:perform -DskipTests -Darguments="-DskipTests"

after_success:
  - bash <(curl -s https://codecov.io/bash)
